### ISSUE TITLE
Input should validate to a number

### ISSUE THREAD

**Issue by miketheman** [lnxchk/Ohno#4]
Executing `knife ohno q` provides interesting output.

**Comment by lnxchk** [comment]
Yeah, this is an interesting one.  So, the command line inputs are always strings, so I'm casting hours using .to_i.  That has the side effect of always casting non-numerical strings to 0. 0 is a legitimate input, so i wouldn't want to take any unexpected action when it is the actual input. 

this works, but it's a bit ugly and verbose:
      if hours == "0"
        new_hours = 0
      else
        new_hours = hours.to_i
        if new_hours == 0
          ui.error "Invalid input. Hours should be an integer"
          exit 1
        end
      end

**Comment by miketheman** [comment]
Potentially, you could add a method to validate:

``` ruby
class HoursInput
    def is_i?
       !!(self =~ /^[-+]?[0-9]+$/)
    end
end
```

Stolen from http://stackoverflow.com/a/1235990

**Comment by lnxchk** [comment]
yeah, let's borrow that regex. i don't want to debug adding classes and overloading methods from within the knife plugin framework. weird shit happens and i don't know enough ruby to fix it. :D

so how about

``` ruby
      if hours =~ /^[0-9]+$/
        new_hours = hours.to_i
      else
        ui.error "Invalid input. Hours should be an integer"
        exit 1
      end
```

**Comment by miketheman** [comment]
That's cool. However, we were considering trying to figure out fractions of an hour, a la `knife ohno 0.5`.

**Comment by lnxchk** [comment]
hrm. that's a whole other mess of time math. the class i'm using, Chef::Knife::Status, has a method time_difference_in_hms that i'm using as a shortcut...

it could be rewritten in minutes, though, with something like...

``` ruby
        mins_diff = now = node["ohai_time"]
        if mins_diff >= new_mins
          ui.msg("#{node['fqdn']}:\t\t" + ui.color("#{mins_diff.to_i} minutes", :red))
        end
```

maybe a new option for ohno, though to make it clean would change the command a bit

``` ruby
  option :hours
    :long => "--hours HOURS",
    :description => "Integer number of hours since last chef-client run"

  option :minutes
    :long => "--minutes MINUTES",
    :description => "Integer number of minutes since last chef-client run"

  option :nocolor
    :long => "--no-color",
    :description => "Turn of color output",
    :boolean => true,
    :default => false
```

**Comment by miketheman** [comment]
Sure, that sounds reasonable.

Default to hours, I guess.

Also: `ui.msg("#{node['fqdn']` should be `node.name`.

**Comment by lnxchk** [comment]
ok. lemme see if i can get this cleaned up. :D

**Comment by miketheman** [comment]
Closing this issue, I think we've got this covered via `knife status -H` now.
